version: '3.9'

services:
  postgres:
    image: postgres:16.3
    container_name: postgress_home
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - home
    ports:
      - 5432:5432
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data

  mysql:
    image: mysql:latest
    container_name: mysql_home
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - home
    ports:
      - 3306:3306
    volumes:
      - ./data/mysqldata:/var/lib/mysql
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  adminer:
    image: adminer
    container_name: adminer_home
    restart: always
    ports:
      - 3307:8080
    networks:
      - home
    depends_on:
      - mysql
      - postgres
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - ADMINER_DEFAULT_SERVER=mysql
      - ADMINER_DEFAULT_USERNAME=${MYSQL_USER}
      - ADMINER_DEFAULT_PASSWORD=${MYSQL_PASSWORD}
      - ADMINER_DEFAULT_DATABASE=${MYSQL_DATABASE}
      
  mongodb:
    image: mongo:latest
    container_name: mongodb_home
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - ./data/mongodata:/data/db
    networks:
      - home

  mongo-express:
    image: mongo-express
    container_name: mongoexpress_home
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - ME_CONFIG_BASICAUTH_USERNAME=${BASIC_AUTH_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${BASIC_AUTH_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=mongodb_home
    depends_on:
      - mongodb
    networks:
      - home

  redis:
    image: redis
    container_name: redis_home
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./data/redis_data:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - home

  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - home

  influxdb:
    image: influxdb:latest
    container_name: influxdb_home
    restart: always
    ports:
      - "8086:8086"
    volumes:
      - ./data/influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=${INFLUXDB_DB}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - INFLUXDB_HTTP_AUTH_ENABLED=true
    networks:
      - home

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_home
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./data/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    networks:
      - home

networks:
  home:
