version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgress_home
    restart: always
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: user_password
      POSTGRES_DB: postgres_db
    networks:
      - home
    ports:
      - 5432:5432
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data

  mysql:
    image: mysql:latest
    container_name: mysql_home
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql_root_password
      MYSQL_DATABASE: mysql_db
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: mysql_password
    networks:
      - home
    ports:
      - 3306:3306
    volumes:
      - ./data/mysqldata:/var/lib/mysql

  mongodb:
    image: mongo:latest
    container_name: mongodb_home
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_password
    ports:
      - 27017:27017
    volumes:
      - ./data/mongodata:/data/db


  mongo-express:
    image: mongo-express
    container_name: mongoexpress_home
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mongo_user
      - ME_CONFIG_MONGODB_ADMINPASSWORD=mongo_password
      - ME_CONFIG_BASICAUTH_USERNAME=basic_user
      - ME_CONFIG_BASICAUTH_PASSWORD=basic_password
      - ME_CONFIG_MONGODB_SERVER=mongodb_home
    depends_on:
      - mongodb



networks:
  home:
