version: '3.9'

services:
  postgres:
    image: postgres:16.3
    container_name: postgress_home
    restart: always
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: user_password
      POSTGRES_DB: postgres_db
    networks:
      - home
    ports:
      - 5432:5432
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data

  mysql:
    image: mysql:latest
    container_name: mysql_home
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql_root_password
      MYSQL_DATABASE: mysql_db
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: mysql_password
    networks:
      - home
    ports:
      - 3306:3306
    volumes:
      - ./data/mysqldata:/var/lib/mysql
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  adminer:
    image: adminer
    container_name: adminer_home
    restart: always
    ports:
      - 3307:8080
    networks:
      - home
    depends_on:
      - mysql
      - postgres
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - ADMINER_DEFAULT_SERVER=mysql
      - ADMINER_DEFAULT_USERNAME=mysql_user
      - ADMINER_DEFAULT_PASSWORD=mysql_password
      - ADMINER_DEFAULT_DATABASE=mysql_db
      
  mongodb:
    image: mongo:latest
    container_name: mongodb_home
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_password
    ports:
      - 27017:27017
    volumes:
      - ./data/mongodata:/data/db
    networks:
      - home


  mongo-express:
    image: mongo-express
    container_name: mongoexpress_home
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mongo_user
      - ME_CONFIG_MONGODB_ADMINPASSWORD=mongo_password
      - ME_CONFIG_BASICAUTH_USERNAME=basic_user
      - ME_CONFIG_BASICAUTH_PASSWORD=basic_password
      - ME_CONFIG_MONGODB_SERVER=mongodb_home
    depends_on:
      - mongodb
    networks:
      - home

  redis:
    image: redis
    container_name: redis_home
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./data/redis_data:/data
    environment:
      - REDIS_PASSWORD=redis_home
    networks:
      - home

  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"    # Porta padrão MQTT
      - "9001:9001"    # Porta WebSockets (opcional)
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - home

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_home
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./data/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin_user
      - GF_SECURITY_ADMIN_PASSWORD=admin_password
    networks:
      - home

networks:
  home:
